dsccommunity/ActiveDirectoryDsc

DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1, DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.schema.mof, DSCResources/MSFT_xADRecycleBin/Tests/ResourceDesigner.Tests.ps1
Added ability to create Forest trusts and fixed Test-xDscResource path in MSFT_xADRecycleBin\Tests\ResourceDesigner.Tests.ps1.
=> Updated xADDomainTrust and xADRecycleBin test

DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
- Fixed invalid domain type when deploying a child domain on windows server 2012r2 I get the following error:
*VERBOSE: [2015-07-24T12:40:29] [ERROR] Unable to find type [Microsoft.DirectoryServices.Deployment.Types.DomainType]*
- Modified "DomainType" parameter to a valid string as shown in here:
https://technet.microsoft.com/en-us/library/hh974722(v=wps.630).aspx
- Invalid parameter "DomainNetbiosName"
- The cmdlet Install-ADDSDomain does not contain a parameter named "DomainNetbiosName", it should be "NewDomainNetbiosName" as shown here:
https://technet.microsoft.com/en-us/library/hh974722(v=wps.630).aspx
VERBOSE: [2015-07-24T12:44:04] [ERROR] A parameter cannot be found that matches parameter name 'DomainNetbiosName'
- There is a flawed "if" statement on Line 132 - always returns …
=> Fixed issues with MSFT_xADDomain.psm1

DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
Due to the DNS client cache the retry loop is ineffective - if the domain did not exist this can be cached which prevents the retry loop from proceeding even once the domain is present. Flushing the DNS client cache between each retry avoids this.
=> Added DNS flush in retry loop

DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.schema.mof, README.md, Tests/xADOrganizationalUnit.Tests.ps1
* Fixes #8 by adding the xADOrganizationalUnit functionality from the PS Gallery
* Adds unit test coverage
* Updated readme with xADOrganizationalUnit details
* Added reference to xADGroup in the unreleased section as this was missing!
The only query I have is around the 'ProtectedFromAccidentalDeletion' parameter.
* This is implemented as a [string] { Yes | No }.
* I have left it as a string for backwards compatibility (would still require a configuration update due to the change in resource name).
* If we are going to change this to a [boolean] now is the best time to do it?!
=> Merges xADOrganizationalUnit from PS Gallery

DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1, DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, README.md, Tests/Unit/MSFT_xADCommon.Tests.ps1, Tests/Unit/MSFT_xADGroup.Tests.ps1, Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1, Tests/Unit/MSFT_xADUser.Tests.ps1
* Adds Get-ADCommonParameters shared function and tests
* Implements shared functions across MSFT_xADGroup, MSFT_xADOrganizationalUnit and MSFT_xADUser resources
* Implements test template for MSFT_xADOrganizationalUnit and MSFT_xADUser
* Adds [CredentialAttribute()] to comply with PSScriptAnalyzer rules
* Renames parameter verbs to comply with PSScriptAnalyzer rules (plurals are still present)
=> Fixes PSScriptAnalyzer warnings

DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
Fixing Script Analyzer errors - in this case the password is already passed as a credential object so it shouldn't pose a security risk and to change it could break other code - thus, I'm just by-passing the rule for these 3 instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/85)
=> supressed PSSA credential rule in example file

.gitignore, DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1, DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1, DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof, DSCResources/MSFT_xADComputer/en-US/MSFT_xADComputer.psd1, DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, README.md, Tests/Unit/MSFT_xADCommon.Tests.ps1, Tests/Unit/MSFT_xADComputer.Tests..ps1, Tests/Unit/MSFT_xADComputer.Tests.ps1, appveyor.yml, xActiveDirectory.psd1
* Ignores DSCResource.Tests
* Updates readme and adds example
* Adds unit test coverage
* Fixes #69
* Fixes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/96)
=> Adds xADComputer Resource

DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1, README.md, Tests/Unit/MSFT_xADDomainController.Tests.ps1
Populate values for DatabasePath, LogPath and SysvolPath during Get-TargetResource. I'm reading them from the registry, where this paths are stored as a configuration for NTDS and Netlogon services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/122)
=> xADDomainController return path

README.md
* Fixed several typos
* Fixed display of UPN in xADUser, line 77. Markdown was seeing `[DNS-domain-name] (optional)` as a trigger to build a hyperlink
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/125)
=> Readme formatting and typos

DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1, README.md
This is the same code that was submitted by @slapointe in #101 with the merge conflicts in the README fixed.
Azure is asking for these fixes for one of their templates that the DSC extension uses.
@TravisEz13 What tests are needed for this PR to go through?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/137)
=> Duplicate of Abandoned PR #101: Handle FaultException race condition during domain creation & reboots. (Fixes #73)

DSCResources/MSFT_xADReplicationSite/MSFT_xADReplicationSite.psm1, DSCResources/MSFT_xADReplicationSite/MSFT_xADReplicationSite.schema.mof, README.md, Tests/Unit/MSFT_xADReplicationSite.Tests.ps1
I've added an DSC resource callled **xADReplicationSite** to add or remove Active Directory Replication Sites. Its an extension to the pull request #180. In addition, it is possible to rename the Default-First-Site-Name instead of creating a new site. This is useful for AD deployments from scratch, where the initial site is called Default-First-Site-Name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/185)
=> Add xADReplicationSite resource.

README.md
- Adding a Branches section to the README.md with Codecov badges for both
master and dev branch (issue #192).
Fixes #192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/193)
=> xActiveDirectory: Adding a Branches section to the README.md

DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1, README.md, Tests/Unit/MSFT_xADGroup.Tests.ps1
Changes to xADGroup to resolve Issue #183. Since the parameters had a default value I had to add checking to see if the parameter was actually bound before setting it. This was true for the GroupScope and Category parameters.
While I was in there I cleaned up a few formatting issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/197)
=> Resolves Issue 183

DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1, DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1, DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof, DSCResources/MSFT_xADComputer/en-US/MSFT_xADComputer.psd1, DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1, DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.schema.mof, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, README.md, Tests/Unit/MSFT_xADCommon.Tests.ps1, Tests/Unit/MSFT_xADComputer.Tests.ps1, Tests/Unit/MSFT_xADDomain.Tests.ps1, Tests/Unit/MSFT_xADDomainController.Tests.ps1, Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1, Tests/Unit/MSFT_xADGroup.Tests.ps1, Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1, Tests/Unit/MSFT_xADServicePrincipalName.Tests.ps1, Tests/Unit/MSFT_xADUser.Tests.ps1
Implemented restoring groups, users, computers and OUs from recycle bin. The resource will throw an error when the restoration cannot be completed due to the container not existing.
Using the new feature is opt-in and requires using the new parameter RestoreFromRecycleBin.
Fixes #211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/217)
=> Implement ad object restore

DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof, README.md, Tests/Unit/MSFT_xADDomainController.Tests.ps1
Added new parameter to allow Installation Media to be used with a new Domain Controller install.
- Fixes #108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/238)
=> xADDomainController: Added new parameter to support IFM

DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1, DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1, Examples/Resources/xADGroup/1-NewGroup.ps1, Examples/Resources/xADGroup/2-NewGroupWithMembers.ps1, Examples/Resources/xADGroup/3-NewGroupMultidomainMembers.ps1, README.md, Tests/Unit/MSFT_xADCommon.Tests.ps1, Tests/Unit/MSFT_xADGroup.Tests.ps1
This PR builds on the work done in #174 by @robbiddle and implements multi-domain group members.
This PR closes #174, which has been marked as abandoned.
- Fixes #152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/240)
=> xADGroup: Implemented multidomain group members (fixes #152, close #174)

DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, README.md, Tests/Unit/MSFT_xADUser.Tests.ps1
Added new parameter to allow Kerberos delegation to be set on an Active Directory user.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/241)
=> xADUser: Add TrustedForDelegation parameter to support Kerberos delegation

CHANGELOG.md, DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof, DSCResources/MSFT_xADDomainController/en-US/MSFT_xADDomainController.strings.psd1, Examples/Resources/xADDomainController/1-AddDomainControllerToDomainMinimal.ps1, Examples/Resources/xADDomainController/2-AddDomainControllerToDomainAllProperties.ps1, Examples/Resources/xADDomainController/3-AddDomainControllerToDomainUsingIFM.ps1, README.md, Tests/Unit/MSFT_xADCommon.Tests.ps1, Tests/Unit/MSFT_xADDomainController.Tests.ps1
- Changes to xADDomainController
- Added new parameter to disable or enable the Global Catalog (GC) (issue #75).
- Fixed a bug with the parameter `InstallationMediaPath` that it would
not be added if it was specified in a configuration. Now the parameter
`InstallationMediaPath` is correctly passed to `Install-ADDSDomainController`.
- Refactored the resource with major code cleanup and localization.
- Updated unit tests to latest unit test template, and refactored the
tests for the function 'Set-TargetResource'.
- Improved test code coverage.
- Fixes #75
- Closes #135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> xADDomainController: Added new parameter IsGlobalCatalog

CHANGELOG.md, DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1, Tests/Unit/MSFT_xADCommon.Tests.ps1
- Changes to xADComputer
- Restoring a computer account from the recycle bin no longer fails if
there are more than one object with the same name in the recycle bin.
Now it uses the object that was changed last using the property
`whenChanged` ([issue #271](https://github.com/PowerShell/xActiveDirectory/issues/271)).
- Changes to xADGroup
- Restoring a group from the recycle bin no longer fails if there are
more than one object with the same name in the recycle bin. Now it
uses the object that was changed last using the property `whenChanged`
([issue #271](https://github.com/PowerShell/xActiveDirectory/issues/271)).
- Changes to xADOrganizationalUnit
- Restoring a organization unit from the recycle bin no longer fails if
there are more than one object with the same name in the recycle …
=> xActiveDirectory: Restoring an object no longer fails

CHANGELOG.md, DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1, DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
- Changes to xADDomain
- Suppressing the Script Analyzer rule `PSAvoidGlobalVars` since the
resource is using the `$global:DSCMachineStatus` variable to trigger
a reboot.
- Changes to xADDomainController
- Suppressing the Script Analyzer rule `PSAvoidGlobalVars` since the
resource is using the `$global:DSCMachineStatus` variable to trigger
a reboot.
- Changes to xWaitForADDomain
- Suppressing the Script Analyzer rule `PSAvoidGlobalVars` since the
resource is using the `$global:DSCMachineStatus` variable to trigger
a reboot.
- Fixes #286 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> xActiveDirectory: Suppressing Script Analyzer rule PSAvoidGlobalVars

CHANGELOG.md, DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof, DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof
Fix RestoreFromRecycleBin description for xADComputer and xADGroup
- Fixes #291 
- Fixes #292 
-->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/308)
=> xActiveDirectory: Fix RestoreFromRecycleBin description

CHANGELOG.md, DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
- Fixes #295 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/313)
=> Fix for issue 295

CHANGELOG.md, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, Tests/Unit/MSFT_xADUser.Tests.ps1
This PR adds the following parameters to the `xADUser` resource:
- AccountNotDelegated
- AllowReversiblePasswordEncryption
- CompoundIdentitySupported
- PasswordNotRequired
- SmartcardLogonRequired
- LogonWorkstations
- Organization
- OtherName
These are all the remaining `String` and `Boolean` parameters available in the `New/Get/Set-ADUser` PowerShell cmdlets.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/373)
=> xADUser: Add Additional Parameters

DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
- Changes to xADComputer
- Removes the helper function Set-DscADComputer from the resource since it has been moved
to the module xActiveDirectory.Common.
n/a
*There are already entries in the change log that covers this change.*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/380)
=> xADComputer: Removes helper function Set-DscADComputer

Tests/Unit/MSFT_xADComputer.Tests.ps1, Tests/Unit/Stubs/ActiveDirectoryStub.psm1, Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
This PR extends the Function and Type stubs that were created for the `xADDomainController` resource tests and adds them into the `xADComputer` resource tests, so that these tests can also be run locally without the `ActiveDirectory` PowerShell module being installed.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/387)
=> xADComputer: Add ActiveDirectory Function and Type Stubs to Tests

CHANGELOG.md, DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1, Tests/Unit/MSFT_xADComputer.Tests.ps1
This PR fixes the Exception that occurs when the `ServicePrincipalNames` property is set to an empty string and is not in the desired state.
Additional tests have been added to test all properties being set to empty strings.
- Fixes #382 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/388)
=> xADComputer: Fix ServicePrincipalNames Empty String Exception

CHANGELOG.md, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, Tests/Unit/MSFT_xADUser.Tests.ps1
This PR fixes the issue that  `Password` property is being updated whenever another property is changed even though it was already in the desired state.
This is achieved by adding a call to the `Test-Password` function from within the relevant code block of the `Set-TargetResource` function.
- Fixes #384 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/389)
=> xADUser: Fix Password Property Being Updated Whenever Another Property is Changed

CHANGELOG.md, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, Tests/Unit/MSFT_xADUser.Tests.ps1
This PR replaces the `Write-Error` statement in the `xADUser` resource with a call to the resource helper function `New-InvalidOperationException` and a relevant test added.
- Fixes #331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/392)
=> xADUser: Replace Write-Error with the correct helper function

CHANGELOG.md, DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1, Tests/Unit/MSFT_xADRecycleBin.Tests.ps1
This PR replaces the `Write-Error` statements in the `xADRecycleBin` resource with calls to the relevant resource helper exception functions.
- Fixes #327 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/393)
=> xADRecycleBin: Replace Write-Error with the correct helper function

CHANGELOG.md, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1, DSCResources/MSFT_xADOrganizationalUnit/en-US/MSFT_xADOrganizationalUnit.strings.psd1
This PR fixes the incorrect verbose message when this resource has `Ensure` set to `Absent`.
- Fixes #276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/396)
=> xADOrganizationalUnit: Verbose Message Fix

CHANGELOG.md, DSCResources/MSFT_xADComputer/en-US/about_xADComputer.help.txt, DSCResources/MSFT_xADDomain/en-US/about_xADDomain.help.txt, DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt, DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/about_xADDomainDefaultPasswordPolicy.help.txt, DSCResources/MSFT_xADDomainTrust/en-US/about_xADDomainTrust.help.txt, DSCResources/MSFT_xADForestProperties/en-US/about_xADForestProperties.help.txt, DSCResources/MSFT_xADGroup/en-US/about_xADGroup.help.txt, DSCResources/MSFT_xADKDSKey/en-US/about_xADKDSKey.help.txt, DSCResources/MSFT_xADManagedServiceAccount/en-US/about_xADManagedServiceAccount.help.txt, DSCResources/MSFT_xADObjectEnabledState/en-US/about_xADObjectEnabledState.help.txt, DSCResources/MSFT_xADObjectPermissionEntry/en-US/about_xADObjectPermissionEntry.help.txt, DSCResources/MSFT_xADOrganizationalUnit/en-US/about_xADOrganizationalUnit.help.txt, DSCResources/MSFT_xADRecycleBin/en-US/about_xADRecycleBin.help.txt, DSCResources/MSFT_xADReplicationSite/en-US/about_xADReplicationSite.help.txt, DSCResources/MSFT_xADReplicationSiteLink/en-US/about_xADReplicationSiteLink.help.txt, DSCResources/MSFT_xADReplicationSubnet/en-US/about_xADReplicationSubnet.help.txt, DSCResources/MSFT_xADServicePrincipalName/en-US/about_xADServicePrincipalName.help.txt, DSCResources/MSFT_xADUser/en-US/about_xADUser.help.txt, DSCResources/MSFT_xWaitForADDomain/en-US/about_xWaitForADDomain.help.txt
This PR adds auto-generated `about_help` files for each resource to the resource specific `en-US` directory. This will be displayed on PowerShell when running `Get-Help` and the specific DSC resource name.
These files were generated with the modified `New-DscResourcePowerShellHelp` function from this PR: PowerShell/DSCResource.Tests#325.
- Fixes #404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/405)
=> xActiveDirectory: Add Auto-Generated 'about_<DSCResource>.help.txt' Files for all Resources

CHANGELOG.md, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1, DSCResources/MSFT_xADOrganizationalUnit/en-US/MSFT_xADOrganizationalUnit.strings.psd1, Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
This PR adds code to the `xADOrganizationalUnit` resource to catch the `ADIdentityNotFoundException` returned by `Get-ADOrganizationalUnit` and return an improved error message.
- Fixes #408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/413)
=> xADOrganizationalUnit: Catch Exception When the Path Property specifies a Non-Existing Path

CHANGELOG.md, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
This PR makes the following changes to the `xADUser` resource:
- Adds an additional Null/Empty parameter & property check to prevent the exception when creating a User with an empty string property.
- Relocates the user move/rename code to after the `Set-ADUser` code and performs the `Move-ADObject` before the `Rename-ADObject` to prevent the exception when updating CommonName and Path at the same time.
- Fixes #402
- Fixes #407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/412)
=> xADUser: Fix CN/Path Concurrent Change and Empty String Property on Creation Exceptions

CHANGELOG.md, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, Tests/Unit/MSFT_xADUser.Tests.ps1
This PR changes the behaviour of the `ChangePasswordAtLogon` property of the `xADUser` resource so that if it is present and set to `true` in the resource, it is only set once at user creation. The current behaviour keeps resetting the property to `true` at every DSC refresh if the user has subsequently changed their password which is not useful.
Also fixed the issue links in the changelog.
- Fixes #414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/417)
=> xADUser: Fix ChangePasswordAtLogon Property to be only set to True at User Creation

CHANGELOG.md, DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1, DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, Modules/xActiveDirectory.Common/en-US/xActiveDirectory.Common.strings.psd1, Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1, Tests/Unit/MSFT_xADDomain.Tests.ps1, Tests/Unit/MSFT_xADKDSKey.Tests.ps1, Tests/Unit/MSFT_xADRecycleBin.Tests.ps1, Tests/Unit/MSFT_xADUser.Tests.ps1, Tests/Unit/xActiveDirectory.Common.Tests.ps1
- Changes to xActiveDirectory
- Removed the helper function `ThrowInvalidOperationError` and `ThrowInvalidArgumentError` in favor of the [new helper functions for localization](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#helper-functions-for-localization) (issue #316, issue #317).
- Cleaned up some minor style violations in the code.
- Fixed an issue that the helper function `Add-ADCommonGroupMember` was
not outputting the correct group name in a verbose message and in an
error message.
- xADDomain
- Updated tests and replaced `Write-Error` with `throw`
(issue #332).
- Changes to xADRecycleBin
- Updated tests and remove unnecessary mocks of `Write-Error`.
- Fixes #316 
- Fixes #317
- Fixes #332
Entry should say what was changed, and how that affects users (if …
=> xActiveDirectory: Remove old helper functions

CHANGELOG.md, DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
This PR addresses issue #341.  It adds comment based help to the xWaitForADDomain resource.
-Fixes #341 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/435)
=> xWaitForADDomain: Fix Issue #341

CHANGELOG.md, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1, DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof, DSCResources/MSFT_xADDomainController/README.md, DSCResources/MSFT_xADDomainController/en-US/MSFT_xADDomainController.strings.psd1, DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt, Examples/Resources/xADDomainController/4-AddReadOnlyDomainController_Config.ps1, Examples/Resources/xADDomainController/4-Read-OnlyDomainController_Config.ps1, Tests/Unit/MSFT_xADDomainController.Tests.ps1, Tests/Unit/Stubs/ActiveDirectoryStub.psm1, Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
Adding support for Read-only Domain Controllers creation.
- Fixes #40
- Replaces PR #390 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/406)
=> xADDomainController: Add RODC Creation Support

CHANGELOG.md, Tests/Unit/MSFT_xADComputer.Tests.ps1, Tests/Unit/MSFT_xADDomain.Tests.ps1, Tests/Unit/MSFT_xADDomainController.Tests.ps1, Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1, Tests/Unit/MSFT_xADDomainTrust.Tests.ps1, Tests/Unit/MSFT_xADGroup.Tests.ps1, Tests/Unit/MSFT_xADKDSKey.Tests.ps1, Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1, Tests/Unit/MSFT_xADObjectEnabledState.Tests.ps1, Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1, Tests/Unit/MSFT_xWaitForADDomain.Tests.ps1
- Changes to xActiveDirectory
- Removed unnecessary Script Analyzer rule overrides from tests.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/436)
=> Remove PSAvoidUsingConvertToSecureStringWithPlainText

CHANGELOG.md, DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1, DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1, DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1, DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
- Fixes #340 
- Fixes #339 
- Fixes #335
- Fixes #330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/440)
=> Fixes Issue #340 #339 #335 #330

CHANGELOG.md, DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1, DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1, DSCResources/MSFT_xADRecycleBin/en-US/MSFT_xADRecycleBin.strings.psd1, Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
- Changes to xADObjectPermissionEntry
- Remove remnants of the `SupportsShouldProcess` (issue #329).
- Changes to xADRecycleBin
- Removed `SupportsShouldProcess` from the resource since DSC does not
support that interactive function (issue #328).
- Changes to xADOrganizationalUnit
- The unit tests are using the stub classes so the tests can be run locally.
Fixes #329 
Fixes #328 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/441)
=> xActiveDirectory: Removing SupportsShouldProcess

CHANGELOG.md, DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
- Changes to ADUser 
- Update the logic for setting the default value for the parameter
`CommonName`. This is due to an how LCM handles parameters when a
default value is derived from another parameter (issue #427).
- Fixes #427 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/460)
=> ADUser: Update the default value logic for CommonName

CHANGELOG.md, DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
- Changes to ADUser
- Now uses the helper function `Add-TypeAssembly` which have some benefit
instead of directly using `Add-Type`, like verbose logging (issue #431).
- Fixes #431 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/458)
=> ADUser: Uses helper function Add-TypeAssembly

CHANGELOG.md, DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.psm1, DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.schema.mof, DSCResources/MSFT_ADDomainTrust/en-US/MSFT_ADDomainTrust.strings.psd1, DSCResources/MSFT_ADDomainTrust/en-US/about_ADDomainTrust.help.txt, Examples/Resources/ADDomainTrust/1-ADDomainTrust_ExternalInboundTrust_Config.ps1, Examples/Resources/ADDomainTrust/2-ADDomainTrust_ExternalInboundTrustWithOptInToRecreate_Config.ps1, Tests/Unit/MSFT_ADDomainTrust.Tests.ps1
- Changes to ADDomain
- BREAKING CHANGE: A new parameter `AllowTrustRecreation` has been added
that when set allows a trust to be recreated in scenarios where that
is required. This way the user have to opt-in to such destructive
action since since it can result in service interruption (issue #421).
- Fixes #421 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/457)
=> BREAKING CHANGE: ADDomain: Add new parameter AllowTrustRecreation

CHANGELOG.md, DSCResources/MSFT_ADUser/MSFT_ADUser.psm1, Tests/Unit/MSFT_ADUser.Tests.ps1
According to DSC Resource Style Guidelines & Best Practices there should be only mandatory parameters in the Get-TargetResource function.
The unused non-mandatory parameters are removed.
- Fixes #293 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/487)
=> ADUser: Remove unused non-mandatory parameters from the Get-TargetResource

.vscode/analyzersettings.psd1, CHANGELOG.md
I have noticed that the default rules for PSScriptAnalyzer were not enabled, although a bunch of them are part of IncludeRules array.
Adding following line in analyzersettings.psd1 would enable them:
IncludeDefaultRules = $true
- Fixes #491 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/492)
=> Enable Default PSSCript Rules

CHANGELOG.md, DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1, Tests/Integration/MSFT_ADGroup.Integration.Tests.ps1, Tests/Integration/MSFT_ADGroup.config.ps1
- Changes to ADGroup
- Now Get-TargetResource returns correct value when the group does not
exist.
- Added integration tests (issue #350).
- Fixes #350 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/495)
=> ADGroup: Add integration tests

CHANGELOG.md, DSCResources/MSFT_ADComputer/README.md, DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt, DSCResources/MSFT_ADGroup/README.md, DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt, DSCResources/MSFT_ADOrganizationalUnit/README.md, DSCResources/MSFT_ADOrganizationalUnit/en-US/about_ADOrganizationalUnit.help.txt, DSCResources/MSFT_ADUser/README.md, DSCResources/MSFT_ADUser/en-US/about_ADUser.help.txt, Tests/Integration/MSFT_ADComputer.Integration.Tests.ps1, Tests/Integration/MSFT_ADComputer.config.ps1, Tests/Integration/MSFT_ADGroup.Integration.Tests.ps1, Tests/Integration/MSFT_ADGroup.config.ps1
- Changes to ADUser
- Added a note to the resource README.md that `RestoreFromRecycleBin`
needs the feature Recycle Bin enabled.
- Changes to ADGroup
- Added a note to the resource README.md that `RestoreFromRecycleBin`
needs the feature Recycle Bin enabled (issue #496).
- Changes to ADOrganizationalUnit
- Added a note to the resource README.md that `RestoreFromRecycleBin`
needs the feature Recycle Bin enabled.
- Changes to ADComputer
- Added a note to the resource README.md that `RestoreFromRecycleBin`
needs the feature Recycle Bin enabled (issue #498).
- Updated integration test to be able to catch when a computer account
cannot be restored.
- Fixes #496
- Fixes #498
---
This change …
=> Update documentation for resource that uses RestoreFromRecycleBin

CHANGELOG.md, DSCResources/MSFT_ADReplicationSite/MSFT_ADReplicationSite.psm1, DSCResources/MSFT_ADReplicationSite/MSFT_ADReplicationSite.schema.mof, DSCResources/MSFT_ADReplicationSite/en-US/MSFT_ADReplicationSite.strings.psd1, DSCResources/MSFT_ADReplicationSite/en-US/about_ADReplicationSite.help.txt, Tests/Integration/MSFT_ADReplicationSite.Integration.Tests.ps1, Tests/Integration/MSFT_ADReplicationSite.config.ps1, Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
This PR will add the ability to configure a Replication Site Description. Will also add integration testing
Fixes #500 
Fixes #355 
Fixes #502 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/501)
=> AdReplicationSite: Adding description attribute, will create integration tests

CHANGELOG.md, Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1, Tests/Unit/ActiveDirectory.Common.Tests.ps1, Tests/Unit/MSFT_ADKDSKey.Tests.ps1, Tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1, Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1, Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1, Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1, Tests/Unit/MSFT_ADServicePrincipalName.Tests.ps1
- Fix more hashtables according to style guidelines (issue #516).
Fixes #516 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/523)
=> ActiveDirectoryDsc: Fix more hashtables according to styleguideline

CHANGELOG.md, Tests/Integration/MSFT_ADKDSKey.Integration.Tests.ps1, Tests/Integration/MSFT_ADKDSKey.config.ps1
This PR adds integration tests for the `ADKDSKey` resource.
- Fixes #351
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/526)
=> ADKDSKey: Add Integration Tests

CHANGELOG.md, DSCResources/MSFT_ADReplicationSite/MSFT_ADReplicationSite.psm1, Tests/Integration/MSFT_ADReplicationSite.Integration.Tests.ps1, Tests/Integration/MSFT_ADReplicationSite.config.ps1, Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
Fix for correct evaluation of `Description` parameter in `Test-TargetResource` of `MSFT_ADReplicationSite` resource. When no description was defined, the test incorrectly evaluated as $false every time.
Fixes #534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/535)
=> MSFT_ADReplicationSite: Fixing Description parameter evaluation

CHANGELOG.md, source/DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1
This PR fixes the `ADReplicationSiteLink` RemovingSites verbose message.
- Fixes #518 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/541)
=> ADReplicationSiteLink: Fix RemovingSites Verbose Message

CHANGELOG.md, Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1, source/DSCResources/MSFT_ADObjectPermissionEntry/MSFT_ADObjectPermissionEntry.psm1, source/DSCResources/MSFT_ADObjectPermissionEntry/en-US/MSFT_ADObjectPermissionEntry.strings.psd1
Fixes issue with ADObjectPermissionEntry resource, where unable to run Get-DscConfiguration or Test-DscConfiguration where the object path of the associated AD resource (on which the PermissionEntry is defined) doesn't exist yet.
- Fixes #552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/555)
=> ADObjectPermissionEntry: Fix Exception When the Object Path Does Not Exist

CHANGELOG.md, source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
This PR solves the issue with the `ADObjectPermissionEntry` resource where the AD PSDrive needs to be created but it is in the wrong scope..
- Fixes #547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/565)
=> ADObjectPermissionEntry: Fix AD PSDrive Scope Issue

CHANGELOG.md, Tests/Unit/MSFT_ADDomain.Tests.ps1, source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1, source/DSCResources/MSFT_ADDomain/en-US/MSFT_ADDomain.strings.psd1
This PR adds the following additional exceptions to the retry mechanism for the `Get-ADDomain` cmdlet that have been shown to occur when the domain controller is initialising:
- `System.Security.Authentication.AuthenticationException`
- `System.InvalidOperationException`
- Fixes #574 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/577)
=> ADDomain: Add Get-ADDomain Additional Retry Exceptions

CHANGELOG.md, Tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
This PR adds support for `msDS-ManagedServiceAccount` and `msDS-GroupManagedServiceAccount` objects to the `ADGroup` resource by patching the `Add-ADCommonGroupMember` function of the `ActiveDirectoryDsc.Common` module.
This PR is a replacement for #533 which was a pre-new CI PR.
- Fixes #532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/578)
=> ADGroup: Add Support for Managed Service Accounts

CHANGELOG.md, Tests/Unit/MSFT_ADDomain.Tests.ps1, source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1
This PR adds the following additional exception to the retry mechanism for the Get-ADDomain cmdlet that have been shown to occur when the domain controller is initialising:
- `System.ArgumentException`
- Fixes #581 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/586)
=> ADDomain: Add Get-ADDomain Additional Retry Exception

CHANGELOG.md, GitVersion.yml, azure-pipelines.yml
- The regular expression for `minor-version-bump-message` in the file
`GitVersion.yml` was changed to only raise minor version when the
commit message contain the word `add`, `adds`, `minor`, `feature`,
or `features`.
- Only run CI pipeline on branch `master` when there are changes to files
inside the `source` folder.
- Fixes #588 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/589)
=> ActiveDirectoryDsc: Fix regex for bumping version

CHANGELOG.md, azure-pipelines.yml
- Fixed the pipeline paths trigger.
This is now according to the docs here https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/599)
=> ActiveDirectoryDsc: Update pipeline paths trigger

CHANGELOG.md, source/DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.psm1, source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psd1, source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
This PR moves the `Get-ActiveDirectoryDomain` and `Get-ActiveDirectoryForest` functions in the `ADDomainTrust` resource into the `ActiveDirectoryDsc.Common` module.
This increases the Code Coverage of the `ADDomainTrust` resource to 100%.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/602)
=> ADDomainTrust: Move Get-ActiveDirectoryDomain and Get-ActiveDirectoryForest Functions into `ActiveDirectoryDsc.Common` Module.

CHANGELOG.md, source/DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1, tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
This PR fixes the issue with the `ADReplicationSiteLink` resource whereby setting `OptionChangeNotification`, `OptionTwoWaySync` or `OptionDisableCompression` fails after the resource is initially created.
- Fixes #605
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/606)
=> ADReplicationSiteLink: Fix Setting Options After the Resource is Initially Created

CHANGELOG.md, RequiredModules.psd1, source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
This PR fixes the CI pipeline by pinning the `Pester` module to `v4.10.1` and updating the `DscResource.Common` module to `v0.9.0`.
It also restores importing the `DscResource.Common` module import in the `ActiveDirectoryDsc.Common` module that was incorrectly disabled.
- Fixes #612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/614)
=> ActiveDirectoryDsc: Fix CI Pipeline and DscResource.Common Module Import

CHANGELOG.md, source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1, tests/Unit/MSFT_ADDomainController.Tests.ps1
This PR fixes an issue with the `ADDomainController` resource whereby the `Test-TargetResource` function will raise an error if the `ReadOnlyReplica` property is set to `true`.
- Fixes #611 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/615)
=> ADDomainController: Fix Test-TargetResource Issue When the 'ReadOnlyReplica' Property is set to 'true'

CHANGELOG.md, azure-pipelines.yml
- Move CI/CD build step to using build worker image `windows-latest`.
None.
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/700)
=> ActiveDirectoryDsc: Use windows-latest for build

CHANGELOG.md, source/DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1
Allow OptionChangeNotification, OptionTwoWaySync and OptionDisableCompression to be updated even if ReplicationFrequencyInMinutes is not set (fixes #637)
- Fixes #637
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/699)
=> ADReplicationSiteLink: Fix for Options when ReplicationFrequencyInMinute not set

CHANGELOG.md, azure-pipelines.yml
- Move test pipeline to Windows PowerShell. The hosted agent was updated
to PowerShell 7.4.1. That broke the ASKDSKey unit tests that has a helper
function (`Copy-ArrayObjects`) that serializes objects.
None.
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/704)
=> Fix pipeline

CHANGELOG.md, source/DSCResources/MSFT_ADKDSKey/MSFT_ADKDSKey.psm1
Fix #702 where 'String was not recognised as a valid DateTime' can occur with non en-US cultures
- Fixes #702 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/703)
=> ADSRootKey: Resolved 'String was not recognized as a valid DateTime' in non-US cultures

CHANGELOG.md, azure-pipelines.yml, source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1, source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.schema.mof, source/DSCResources/MSFT_ADDomain/en-US/about_ADDomain.help.txt, source/DSCResources/MSFT_ADKDSKey/MSFT_ADKDSKey.psm1, source/Examples/Resources/ADDomain/3-ADDomain_NewDomainTree_Config.ps1, tests/Unit/MSFT_ADDomain.Tests.ps1
ADDomain resource: Add DomainType support
NB I'm not sure if this is completely correct but am having a go anyway! In particular I couldn't find a way to 'get' the current DomainType for a domain so Get-TargetResource should just return $null - is that OK?
- Fixes #689
- Fixes #692 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705)
=> ADDomain: Add DomainType support

CHANGELOG.md, source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1, source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof, source/DSCResources/MSFT_ADDomainController/en-US/MSFT_ADDomainController.strings.psd1, source/DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt, source/Examples/Resources/ADDomainController/4-ADDomainController_AddReadOnlyDomainController_Config.ps1, tests/Unit/MSFT_ADDomainController.Tests.ps1, tests/Unit/Stubs/ActiveDirectory_2019.psm1, tests/Unit/Stubs/README.md
When setting up a read-only domain controller, it is possible to supply a user or group which will gain local administrative privileges to the RODC. The specified user or members of the specified group can perform operations on the RODC with privileges equivalent to the computer's Administrators group. They aren't members of the Domain Admins or domain built-in Administrators groups.
https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/rodc/install-a-windows-server-2012-active-directory-read-only-domain-controller--rodc---level-200-#delegation-of-rodc-installation-and-administration
This can be selected during initial setup via the DelegatedAdministratorAccountName parameter, but also updated later using the ManagedBy attribute on the computer account in Active …
=> ADDomainController: Support for supplying DelegatedAdministratorAccountName

CHANGELOG.md, source/DSCResources/MSFT_ADObjectPermissionEntry/MSFT_ADObjectPermissionEntry.psm1, tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
Fixes #675 - when using ADObjectPermissionEntry to configure an ACL on a Path that requires escaping (comma, backslash, hash, plus etc), the command fails with 'The object name has bad syntax'
- Fixes #675
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/716)
=> ADObjectPermissionEntry: Fix escaping issue when getting/setting ACLs

CHANGELOG.md, source/DSCResources/MSFT_ADObjectPermissionEntry/MSFT_ADObjectPermissionEntry.psm1, source/DSCResources/MSFT_ADObjectPermissionEntry/en-US/MSFT_ADObjectPermissionEntry.strings.psd1, tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
Resolves the issue described in #724 where ADObjectPermissionEntry has stopped working on Server 2016 (still works on 2012, 2019, 2022, 2025).
- Fixes #724 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/725)
=> ADObjectPermissionEntry: Resolve Windows Server 2016 PSPath issue

CHANGELOG.md, source/DSCResources/MSFT_ADManagedServiceAccount/MSFT_ADManagedServiceAccount.psm1, tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
ADManagedServiceAccount: Set properties KeberosEncryptionType and TrustedForDelegation properly on account creation.
Both properties were not considered previously when the account was created.
- Fixes #650
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/722)
=> ADManagedServiceAccount: Fixed KeberosEncryptionType and TrustedForDelegation on account creation

CHANGELOG.md, source/DSCResources/MSFT_ADObjectPermissionEntry/MSFT_ADObjectPermissionEntry.psm1
Fixes regression uncovered in #727. We started using Join-Path but this doesn't work with the output of Get-ADDrivePSPath
- Fixes #727
help.
=> ADObjectPermissionEntry: Fix regression in 6.6.1 using Join-Path

CHANGELOG.md, source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1, source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.schema.mof, source/DSCResources/MSFT_ADDomain/en-US/about_ADDomain.help.txt, source/DSCResources/MSFT_ADDomainFunctionalLevel/MSFT_ADDomainFunctionalLevel.psm1, source/DSCResources/MSFT_ADDomainFunctionalLevel/MSFT_ADDomainFunctionalLevel.schema.mof, source/DSCResources/MSFT_ADDomainFunctionalLevel/en-US/about_ADDomainFunctionalLevel.help.txt, source/DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.psm1, source/DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.schema.mof, source/DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt, source/DSCResources/MSFT_ADUser/MSFT_ADUser.PropertyMap.psd1, source/DSCResources/MSFT_ADUser/MSFT_ADUser.psm1, source/DSCResources/MSFT_ADUser/MSFT_ADUser.schema.mof, source/DSCResources/MSFT_ADUser/en-US/about_ADUser.help.txt, tests/Integration/MSFT_ADUser.config.ps1, tests/Unit/MSFT_ADUser.Tests.ps1
Adds support for Windows Server 2025 Forest and Domain functional levels
Adds support for some new attributes in ADUser
- Fixes #721 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/730)
=> ADDomain, ADDomainFunctionalLevel, ADForestFunctionalLevel, ADUser - Server 2025 support, new attributes
