- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof
- README.md
- Tests/xADGroup.Tests.ps1
- appveyor.yml
* Implements new xADGroup resource to fix issue #33.
* Adds test coverage for xADGroup
* Updates readme with new functionality
* As per the discussions, this only creates AD groups
* The xADGroupMember functionality will be merged in afterwards
> Implements xADGroup

- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof
- README.md
- Tests/xADGroup.Tests.ps1
* Adds Members, MembersToInclude, MembersToExclude and MembershipAttribute properties
* Adds ManagedBy and Notes properties
* Adds test coverage
* Formatting updates inline with defined guidelines
* Updates readme.md
> Implements xADGroup Membership support

- DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1
- DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
- DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
- DSCResources/MSFT_xADDomain/MSFT_xADDomain.schema.mof
- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- README.md
- Tests/Unit/MSFT_xADCommon.Tests.ps1
- Tests/Unit/MSFT_xADDomain.Tests.ps1
- Tests/Unit/MSFT_xADGroup.Tests.ps1
* Rewrite of MSFT_xADDomain adding additional validation and verbose output to fix #27, #32, #53
* Adds ExcludeDns property to MSFT_xADDomain to fix #38
* Moves common functions to MSFT_xADCommon module to consolidate functions
* Updates MSFT_xADGroup tests and adds tests for MSFT_xADDomain to fix #56
* Updates readme with missing properties/descriptions
> xADDomain Rewrite and Function Consolidation

- README.md
> Fixes contribution link

- DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1
- DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.psm1
- DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.schema.mof
- README.md
- Tests/Unit/MSFT_xADCommon.Tests.ps1
- Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1
> Adds xADDomainDefaultPasswordPolicy

- README.md
Noticed that syntax highlighting wasn't working in the readme so fixed. Please consider pulling this minor change in.
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/92)
> fix syntax highlighting

- Assert-HADC.ps1
- Assert-ParentChildDomains.ps1
- DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
- Tests/Unit/MSFT_xADCommon.Tests.ps1
- Tests/Unit/MSFT_xADDomain.Tests.ps1
- Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1
- Tests/Unit/MSFT_xADGroup.Tests.ps1
- Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
- Tests/Unit/MSFT_xADUser.Tests.ps1
- Tests/Unit/MSFT_xWaitForADDomain.Tests.ps1
This is a hotfix for release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/103)
> Supressing PSSA errors for release.

- README.md
- appveyor.yml
As per:
https://github.com/PowerShell/DscResources/issues/147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/105)
>  Converted AppVeyor.yml to pull Pester from PSGallery instead of Chocolatey

- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- README.md
- Tests/Unit/MSFT_xADGroup.Tests.ps1
Fixes #106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/107)
> Passes credentials through to Set-ADGroup and Move-ADGroup cmdlets

- DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1
- DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
- DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof
- README.md
- Tests/Unit/MSFT_xADDomainController.Tests.ps1
- Add possibility to set Site for domain controller
- Add tests for new Site functionality
- Updates README
- Closes #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/109)
> Add Site property to xADDomainController. Close #76

- Tests/Unit/MSFT_xADCommon.Tests.ps1
- Tests/Unit/MSFT_xADDomain.Tests.ps1
- Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1
- Tests/Unit/MSFT_xADGroup.Tests.ps1
- Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
- Tests/Unit/MSFT_xADUser.Tests.ps1
- Tests/Unit/MSFT_xWaitForADDomain.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/89)
> updated tests to not be dependent on git - also delete DSCResource.Tests file.... was there a reason this was in here?

- DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
- README.md
- Tests/Unit/MSFT_xADDomainController.Tests.ps1
* Adds unit test for this scenario
* Adds check if sitename was specified or not
* Fixes #119 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/126)
> Fix #119. SiteName should not be required.

- DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
- README.md
- Tests/Unit/MSFT_xADDomainController.Tests.ps1
- appveyor.yml
- xActiveDirectory.psd1
Releasing version 2.15.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/129)
> Release of version 2.15.0.0 of xActiveDirectory

- DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
- README.md
- Tests/Unit/MSFT_xADDomainController.Tests.ps1
- appveyor.yml
- xActiveDirectory.psd1
Releasing version 2.16.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/138)
> Release of version 2.16.0.0 of xActiveDirectory

- .MetaTestOptIn.json
- .codecov.yml
- README.md
- appveyor.yml
* Converted AppVeyor.yml to use DSCResource.tests shared code.
* Opted-In to markdown rule validation.
* Readme.md modified resolve markdown rule violations.
* Added CodeCov.io support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/145)
> Converted to Use Shared DSCResources Code and CodeCov.io - Fixes #143

- DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.psm1
- DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.schema.mof
- README.md
- Tests/Unit/MSFT_xADReplicationSubnet.Tests.ps1
I've added an DSC resource callled xADReplicationSubnet to add, update or remove Active Directory Replication Subnets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/180)
> Add xADReplicationSubnet resource.

- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
Get will fail if their is only one member.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/173)
> Converted $Members to an Array

- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- DSCResources/MSFT_xADReplicationSite/MSFT_xADReplicationSite.psm1
- DSCResources/MSFT_xADReplicationSite/MSFT_xADReplicationSite.schema.mof
- DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.psm1
- DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.schema.mof
- README.md
- Tests/Unit/MSFT_xADReplicationSite.Tests.ps1
- Tests/Unit/MSFT_xADReplicationSubnet.Tests.ps1
- xActiveDirectory.psd1
Releasing version 2.18.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/188)
> Release of version 2.18.0.0 of xActiveDirectory

- .github/stale.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/204)
> Activate the GitHub App Stale on the GitHub repository

- .gitattributes
- .gitignore
- .vscode/analyzersettings.psd1
- .vscode/settings.json
- README.md
- appveyor.yml
- Update appveyor.yml to use the default template.
- Added default template files .gitattributes, and .gitignore, and
.vscode folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/229)
> Update to use template files

- README.md
- xActiveDirectory.psd1
Releasing version 2.23.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/237)
> Release of version 2.23.0.0 of xActiveDirectory

- README.md
- Tests/Unit/MSFT_xADComputer.Tests.ps1
- Tests/Unit/MSFT_xADUser.Tests.ps1
* Changes to xADComputer
* Minor clean up of unit tests.
* Changes to xADUser
* Minor clean up of unit tests.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/250)
> Fix build errors

- DSCResources/CommonResourceHelper.psm1
- DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
- DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof
- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
- DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.psm1
- DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.schema.mof
- DSCResources/MSFT_xADReplicationSiteLink/en-US/MSFT_xADReplicationSiteLink.strings.psd1
- DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
- DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
- Examples/Resources/xADGroup/1-NewGroup.ps1
- Examples/Resources/xADGroup/2-NewGroupWithMembers.ps1
- Examples/Resources/xADGroup/3-NewGroupMultidomainMembers.ps1
- Examples/Resources/xADReplicationSiteLInk/1-CreateReplicationSiteLink.ps1
- Examples/Resources/xADReplicationSiteLInk/2-ModifyExistingReplicationSiteLink.ps1
- README.md
- Tests/Unit/CommonResourceHelper.tests.ps1
- Tests/Unit/MSFT_xADCommon.Tests.ps1
- Tests/Unit/MSFT_xADComputer.Tests.ps1
- Tests/Unit/MSFT_xADDomainController.Tests.ps1
- Tests/Unit/MSFT_xADGroup.Tests.ps1
- Tests/Unit/MSFT_xADObjectPermissionEntry.Tests.ps1
- Tests/Unit/MSFT_xADReplicationSiteLink.tests.ps1
- Tests/Unit/MSFT_xADUser.Tests.ps1
- Tests/Unit/Stubs/ActiveDirectoryStub.psm1
- Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
- xActiveDirectory.psd1
Releasing version 2.25.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/253)
> Release of version 2.25.0.0 of xActiveDirectory

- DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
- DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.schema.mof
- DSCResources/MSFT_xADManagedServiceAccount/en-US/MSFT_xADManagedServiceAccount.strings.psd1
- README.md
- Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1
- Added Localization using template
- Fixed a few styling issues
- Added in template error messages and now checking for specific errors in test cases
- Removed Enabled parameter as write and made it read (There are some issues right now which won't allow you to Enable/Disable), will open an Issue to fix later
- Updated schema to match the descriptions in the docstrings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/261)
> xADManagedServiceAccount: Fixed a few styling issues

- README.md
This PR fixes the module name reference in the README
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/363)
> xActiveDirectory: Fix Module Name reference in README

- .github/PULL_REQUEST_TEMPLATE.md
Now that the resource documentation is moved to the Wiki and using auto-documentation, the Pull Request template is not quite correct. This PR modifies it as follows:
- Specify to update the resource documentation in the resource directory README.md.
- Remove the README.md from the parameter descriptions update.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/372)
> xActiveDirectory: Update PULL_REQUEST_TEMPLATE.md

- DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
This PR adds the missing `pwdLastSet` ADProperty to the `ChangePasswordAtLogon` adPropertyMap for #371 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/376)
> xADUser: Add pwdLastSet ADProperty to ChangePasswordAtLogon

- DSCResources/MSFT_xADObjectEnabledState/MSFT_xADObjectEnabledState.psm1
- Changes to xADObjectEnabledState
- Fix the synopsis in the comment-based help of the function Compare-TargetResourceState.
*Already an entry in the chnage log that covers this.* 
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/378)
> xADObjectEnabledState: Update comment-based help

- DSCResources/MSFT_xADComputer/README.md
- DSCResources/MSFT_xADDomainTrust/README.md
- DSCResources/MSFT_xADKDSKey/README.md
- DSCResources/MSFT_xADManagedServiceAccount/README.md
- DSCResources/MSFT_xADOrganizationalUnit/README.md
- DSCResources/MSFT_xADReplicationSite/README.md
- DSCResources/MSFT_xADReplicationSiteLink/README.md
- DSCResources/MSFT_xADServicePrincipalName/README.md
- DSCResources/MSFT_xADUser/README.md
- DSCResources/MSFT_xWaitForADDomain/README.md
This PR adds and/or expands the resource descriptions in the individual resource specific README.md files. These files are used to build the Wiki documentation.
The following resource descriptions have been updated:
- xADDomainTrust
- xADReplicationSite
- xADReplicationSiteLink
- xADUser
- xADComputer
- xADKDSKey
- xADManagedServiceAccount
- xADOrganizationalUnit
- xADServicePrincipalName
- xWaitForADDomain
- Fixes #383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/386)
> xActiveDirectory: Add Resource Descriptions

- CHANGELOG.md
- Examples/README.md
This PR adds the resources that were missing to the Example List README.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/391)
> xActiveDirectory: Update Example List README with missing Resources

- CHANGELOG.md
- Examples/Resources/xADComputer/3-AddComputerAccountSpecificPath_Config.ps1
This PR fixes the GUID in the `xADComputer` example `3-AddComputerAccountSpecificPath_Config`.
- Fixes #410 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/411)
> xADComputer: Fix Example 3-AddComputerAccountSpecificPath_Config GUID

- DSCResources/MSFT_xADComputer/en-US/about_xADComputer.help.txt
- DSCResources/MSFT_xADDomain/en-US/about_xADDomain.help.txt
- DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt
- DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/about_xADDomainDefaultPasswordPolicy.help.txt
- DSCResources/MSFT_xADDomainTrust/en-US/about_xADDomainTrust.help.txt
- DSCResources/MSFT_xADForestProperties/en-US/about_xADForestProperties.help.txt
- DSCResources/MSFT_xADGroup/en-US/about_xADGroup.help.txt
- DSCResources/MSFT_xADKDSKey/en-US/about_xADKDSKey.help.txt
- DSCResources/MSFT_xADManagedServiceAccount/en-US/about_xADManagedServiceAccount.help.txt
- DSCResources/MSFT_xADObjectEnabledState/en-US/about_xADObjectEnabledState.help.txt
- DSCResources/MSFT_xADObjectPermissionEntry/en-US/about_xADObjectPermissionEntry.help.txt
- DSCResources/MSFT_xADOrganizationalUnit/en-US/about_xADOrganizationalUnit.help.txt
- DSCResources/MSFT_xADRecycleBin/en-US/about_xADRecycleBin.help.txt
- DSCResources/MSFT_xADReplicationSite/en-US/about_xADReplicationSite.help.txt
- DSCResources/MSFT_xADReplicationSiteLink/en-US/about_xADReplicationSiteLink.help.txt
- DSCResources/MSFT_xADReplicationSubnet/en-US/about_xADReplicationSubnet.help.txt
- DSCResources/MSFT_xADServicePrincipalName/en-US/about_xADServicePrincipalName.help.txt
- DSCResources/MSFT_xADUser/en-US/about_xADUser.help.txt
- DSCResources/MSFT_xWaitForADDomain/en-US/about_xWaitForADDomain.help.txt
A PR was merged in the test framework fixing the cmdlet that generates the *.help.txt so the files are generated with UTF-8 (and not UTF-8 with BOM).
*Already an entry in the change log that covers this change.*
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/433)
> xActiveDirectory: Fix BOM in *.help.txt

- CHANGELOG.md
- DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
- Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
- Changes to xActiveDirectory.Common:
- Removed unused parameter `ModuleName` from `Assert-MemberParameters` function.
- Removed unused parameter `ModuleName` from `ConvertTo-DeploymentForestMode` function.
- Removed unused parameter `ModuleName` from `ConvertTo-DeploymentDomainMode` function.
- Added function help ([issue #321](https://github.com/PowerShell/xActiveDirectory/issues/321)).
- Fixes #321
@johlju - all yours :grin:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xactivedirectory/444)
> Add Comment Based Help to all xActiveDirectory.Common Functions - Fixes #321

- CHANGELOG.md
- DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt
- DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
- Examples/Resources/ADComputer/5-ADComputer_CreateClusterComputerAccount_Config.ps1
- Examples/Resources/ADObjectEnabledState/1-ADObjectEnabledState_EnabledComputerAccount_Config.ps1
- Examples/Resources/ADObjectEnabledState/3-ADObjectEnabledState_EnabledPrestagedClusterComputerAccount_Config.ps1
- Examples/Resources/ADUser/2-ADUser_CreateUserAndIgnorePasswordChanges_Config.ps1
- Examples/Resources/WaitForADDomain/2-WaitForADDomain_WaitForDomainControllerUsingBuiltInCredential_Config.ps1
- Examples/Resources/WaitForADDomain/3-WaitForADDomain_WaitForDomainControllerUsingCredential_Config.ps1
- Examples/Resources/WaitForADDomain/4-WaitForADDomain_WaitForDomainControllerInSite_Config.ps1
- Examples/Resources/WaitForADDomain/5-WaitForADDomain_WaitForDomainControllerWithReboot_Config.ps1
- Examples/Resources/WaitForADDomain/6-WaitForADDomain_WaitForDomainControllerWithLongerDelay_Config.ps1
- Fix examples that had duplicate guid that would have prevented them
to be published.
- Changes to ADComputer
- Add example showing how to create cluster computer account (issue #401).
- Fixes #401 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/461)
> ADComputer: Add example to create cluster computer account

- CHANGELOG.md
- Tests/Integration/MSFT_ADComputer.Integration.Tests.ps1
- Tests/Integration/MSFT_ADDomainTrust.Integration.Tests.ps1
- Tests/Integration/MSFT_ADUser.Integration.Tests.ps1
- Integration tests are now correctly evaluates the value from `Test-DscConfiguration` (issue #434).
- Fixes #434 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/459)
> ActiveDirectoryDsc: Integration tests correctly evaluates Test-DscConfiguration

- CHANGELOG.md
- DSCResources/MSFT_ADComputer/MSFT_ADComputer.psm1
- DSCResources/MSFT_ADDomainDefaultPasswordPolicy/MSFT_ADDomainDefaultPasswordPolicy.psm1
- DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
- DSCResources/MSFT_ADGroup/MSFT_ADGroup.schema.mof
- DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
- Changes to ADGroup
- Added comment-based help (issue #338).
- Update the documentation with the correct default value for the parameter
GroupScope.
- Changes to ADDomainDefaultPasswordPolicy
- Added comment-based help (issue #336).
- Fixes #338 
- Fixes #336 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/464)
> ActiveDirectoryDsc: Fix comment based help

- ActiveDirectoryDsc.psd1
- CHANGELOG.md
- Module manifest has been updated to optimize module auto-discovery (issue #463).
Partly #463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/470)
> ActiveDIrectoryDsc: Updated to optimize module auto-discovery

- CHANGELOG.md
- DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1
- DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof
- DSCResources/MSFT_ADDomainController/README.md
- DSCResources/MSFT_ADDomainController/en-US/MSFT_ADDomainController.strings.psd1
- DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
- DSCResources/MSFT_ADOptionalFeature/en-US/about_ADOptionalFeature.help.txt
- Examples/Resources/ADDomainController/5-ADDomainController_AddDomainControllerAndMoveRole_Config.ps1
- Tests/Unit/MSFT_ADDomainController.Tests.ps1
- Tests/Unit/Stubs/ActiveDirectoryStub.psm1
- Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
- Changes to ADDomainController
- Added new parameter `FlexibleSingleMasterOperationRole` to able to move
Flexible Single Master Operation (FSMO) roles to the current node.
It does not allow seizing of roles, only allows a move when both
domain controllers are available (issue #55).
- Fixes #55 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/472)
> ADDomainController: Added new parameter FlexibleSingleMasterOperationRole

- CHANGELOG.md
- Tests/Unit/ActiveDirectory.Common.Tests.ps1
- Tests/Unit/MSFT_ADDomain.Tests.ps1
- Tests/Unit/MSFT_ADDomainController.Tests.ps1
- Tests/Unit/MSFT_ADDomainDefaultPasswordPolicy.Tests.ps1
- Tests/Unit/MSFT_ADForestProperties.Tests.ps1
- Tests/Unit/MSFT_ADGroup.Tests.ps1
- Tests/Unit/MSFT_ADKDSKey.Tests.ps1
- Tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
- Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
- Tests/Unit/MSFT_ADOptionalFeature.Tests.ps1
- Tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
- Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
- Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
- Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1
- Tests/Unit/MSFT_ADServicePrincipalName.Tests.ps1
- Tests/Unit/MSFT_ADUser.Tests.ps1
- Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
- Update all tests to use `| Should -BeTrue` and `| Should -BeFalse'`.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/473)
> ActiveDirectoryDsc: Update all tests to use BeTrue and BeFalse

- CHANGELOG.md
- DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
- DSCResources/MSFT_ADDomainControllerProperties/MSFT_ADDomainControllerProperties.psm1
- DSCResources/MSFT_ADDomainControllerProperties/MSFT_ADDomainControllerProperties.schema.mof
- DSCResources/MSFT_ADDomainControllerProperties/README.md
- DSCResources/MSFT_ADDomainControllerProperties/en-US/MSFT_ADDomainControllerProperties.strings.psd1
- DSCResources/MSFT_ADDomainControllerProperties/en-US/about_ADDomainControllerProperties.help.txt
- Examples/README.md
- Examples/Resources/ADDomainControllerProperties/1-ADDomainControllerProperties_SetContentFreshness_Config.ps1
- Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
- Tests/Integration/MSFT_ADDomainControllerProperties.Integration.Tests.ps1
- Tests/Integration/MSFT_ADDomainControllerProperties.config.ps1
- Tests/Integration/MSFT_ADObjectEnabledState.config.ps1
- Tests/Unit/ActiveDirectory.Common.Tests.ps1
- Tests/Unit/MSFT_ADDomainControllerProperties.Tests.ps1
- Tests/Unit/MSFT_ADObjectEnabledState.Tests.ps1
- New resource ADDomainControllerProperties (issue #301).
Gist for the integration test output: https://gist.github.com/johlju/05036498cfcc3ab31c2dd84b4e0e21bb
- Fixes #301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/474)
> ADDomainControllerProperties: New resource

- CHANGELOG.md
- DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.psm1
- DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.schema.mof
- DSCResources/MSFT_ADForestFunctionalLevel/README.md
- DSCResources/MSFT_ADForestFunctionalLevel/en-US/MSFT_ADForestFunctionalLevel.strings.psd1
- DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
- Examples/README.md
- Examples/Resources/ADForestFunctionalLevel/1-ADForestFunctionalLevel_SetLevel_Config.ps1
- Tests/Integration/MSFT_ADForestFunctionalLevel.Integration.Tests.ps1
- Tests/Integration/MSFT_ADForestFunctionalLevel.config.ps1
- Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
- Tests/Unit/Stubs/ActiveDirectoryStub.psm1
- New resource ADForestFunctionalLevel (issue #200).
- Partly fixes #200 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/475)
> ADForestFunctionalLevel: New resource

- CHANGELOG.md
- DSCResources/MSFT_ADDomainFunctionalLevel/MSFT_ADDomainFunctionalLevel.psm1
- DSCResources/MSFT_ADDomainFunctionalLevel/MSFT_ADDomainFunctionalLevel.schema.mof
- DSCResources/MSFT_ADDomainFunctionalLevel/README.md
- DSCResources/MSFT_ADDomainFunctionalLevel/en-US/MSFT_ADDomainFunctionalLevel.strings.psd1
- DSCResources/MSFT_ADDomainFunctionalLevel/en-US/about_ADDomainFunctionalLevel.help.txt
- DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.psm1
- DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.schema.mof
- DSCResources/MSFT_ADForestFunctionalLevel/en-US/MSFT_ADForestFunctionalLevel.strings.psd1
- DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
- Examples/README.md
- Examples/Resources/ADDomainFunctionalLevel/1-ADDomainFunctionalLevel_SetLevel_Config.ps1
- Tests/Integration/MSFT_ADDomainFunctionalLevel.Integration.Tests.ps1
- Tests/Integration/MSFT_ADDomainFunctionalLevel.config.ps1
- Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
- Tests/Unit/Stubs/ActiveDirectoryStub.psm1
- New resource ADDomainFunctionalLevel (issue #200).
- Fixes #200 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/476)
> ADDomainFunctionalLevel: New resource

- CHANGELOG.md
- Examples/Resources/WaitForADDomain/1-WaitForADDomain_WaitForDomainController_Config.ps1
- Examples/Resources/WaitForADDomain/2-WaitForADDomain_WaitForDomainControllerUsingBuiltInCredential_Config.ps1
- Examples/Resources/WaitForADDomain/3-WaitForADDomain_WaitForDomainControllerUsingCredential_Config.ps1
- Examples/Resources/WaitForADDomain/4-WaitForADDomain_WaitForDomainControllerInSite_Config.ps1
- Examples/Resources/WaitForADDomain/5-WaitForADDomain_WaitForDomainControllerWithReboot_Config.ps1
- Examples/Resources/WaitForADDomain/6-WaitForADDomain_WaitForDomainControllerWithLongerDelay_Config.ps1
This PR fixes several grammar issues in the `xWaitForADDomain` example descriptions.
It also fixes the alignment of the parameter values in a couple of the examples.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/480)
> xWaitForADDomain: Correct Grammar Issues in Example Descriptions

- Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
- Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
The new resources was tested in the worng APpVeyor job, this resolves the prior merged PR thar missed these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/482)
> ActiveDirectoryDsc: Move unit test to correct appveyor job

- CHANGELOG.md
- DSCResources/MSFT_WaitForADDomain/MSFT_WaitForADDomain.psm1
- DSCResources/MSFT_WaitForADDomain/MSFT_WaitForADDomain.schema.mof
- DSCResources/MSFT_WaitForADDomain/README.md
- DSCResources/MSFT_WaitForADDomain/en-US/MSFT_WaitForADDomain.strings.psd1
- DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
- Examples/Resources/WaitForADDomain/7-WaitForADDomain_WaitForDomainControllerIgnoringAuthenticationErrors_Config.ps1
- Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
- Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
- Tests/Unit/ActiveDirectory.Common.Tests.ps1
- Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
- Changes to ActiveDirectoryDsc.Common
- Updated common helper function `Find-DomainController` with the
optional parameter `WaitForValidCredentials` which will ignore
authentication exceptions when the credentials cannot be authenticated.
- Changes to WaitForADDomain
- An optional parameter `WaitForValidCredentials` can be set to $true
to tell the resource to ignore authentication errors (issue #478).
- Fixes #478 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/481)
> WaitForADDomain: Adds optional parameter WaitForValidCredentials

- CHANGELOG.md
- DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
- DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
- DSCResources/MSFT_ADGroup/MSFT_ADGroup.schema.mof
- DSCResources/MSFT_ADGroup/en-US/MSFT_ADGroup.strings.psd1
- DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
- Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
- Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
- Tests/Integration/MSFT_ADGroup.Integration.Tests.ps1
- Tests/Integration/MSFT_ADGroup.config.ps1
- Tests/Unit/ActiveDirectory.Common.Tests.ps1
- Tests/Unit/MSFT_ADGroup.Tests.ps1
- Changes to ActiveDirectoryDsc.Common
- Update helper function `Add-ADCommonGroupMember` to reduce duplicated
code, and add an evaluation if `Members` is empty.
- Updated helper function `Restore-ADCommonObject` to write out a verbose
message when no object was found in the recycle bin.
- Updated helper function `Assert-MemberParameters` to not throw an error
if the parameter `Members` is en empty array.
- Changes to ADGroup
- Added a read-only property `DistinguishedName`.
- Refactor the function `Set-TargetResource` to use the function
`Get-TargetResource` so that `Set-TargetResource` can correctly throw
an error when something goes wrong (issue #151, issue #166, issue #493).
- It is now possible to enforce a group with no members by using
`Members = @()` in a configuration (issue …
> ADGroup: Fix issue #151, issue #189, issue #493

- CHANGELOG.md
- DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
- Resolved custom Script Analyzer rules that was added to the test framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/508)
> ActiveDirectoryDsc: Resolved custom Script Analyzer rules

- CHANGELOG.md
- Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
- Tests/Unit/ActiveDirectory.Common.Tests.ps1
This PR fixes the `Test-DscPropertyState` function in the `ActiveDirectoryDsc.Common` module so that it correctly handles comparing $null and arrays.
- Fixes #513 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/514)
> ActiveDirectoryDsc.Common: Fix Test-DscPropertyState Failing when Comparing $Null and Arrays

- CHANGELOG.md
- DSCResources/MSFT_ADComputer/MSFT_ADComputer.psm1
- DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.psm1
- DSCResources/MSFT_ADForestProperties/MSFT_ADForestProperties.psm1
- DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1
- DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1
- DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
All hashtables that does not comply with the custom PSSA were corrected.
- Fixes #516 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/521)
> Resolve style guideline violations for hashtables

- CHANGELOG.md
- Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
- Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
- Tests/Unit/ActiveDirectory.Common.Tests.ps1
This PR adds additional checks to the `Assert-ADPSDrive` function to test if the `ActiveDirectory` PS Provider is installed, and forces an import of the `ActiveDirectory` module if it isn't.
The unit tests for `Assert-ADPSDrive` were also refactored to make use of nested contexts.
- Fixes #527 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/activedirectorydsc/528)
> ADObjectPermissionEntry: Update Assert-ADPSDrive with PSProvider Checks

- CHANGELOG.md
- README.md
This PR updates the ActiveDirectoryDsc Wiki link in the `README.md` file.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/539)
> ActiveDirectoryDsc: Update Wiki link in README.md

- CHANGELOG.md
- source/DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt
- source/DSCResources/MSFT_ADDomain/en-US/about_ADDomain.help.txt
- source/DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
- source/DSCResources/MSFT_ADDomainDefaultPasswordPolicy/en-US/about_ADDomainDefaultPasswordPolicy.help.txt
- source/DSCResources/MSFT_ADDomainFunctionalLevel/en-US/about_ADDomainFunctionalLevel.help.txt
- source/DSCResources/MSFT_ADDomainTrust/en-US/about_ADDomainTrust.help.txt
- source/DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
- source/DSCResources/MSFT_ADForestProperties/en-US/about_ADForestProperties.help.txt
- source/DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
- source/DSCResources/MSFT_ADManagedServiceAccount/en-US/about_ADManagedServiceAccount.help.txt
- source/DSCResources/MSFT_ADObjectEnabledState/en-US/about_ADObjectEnabledState.help.txt
- source/DSCResources/MSFT_ADObjectPermissionEntry/en-US/about_ADObjectPermissionEntry.help.txt
- source/DSCResources/MSFT_ADOptionalFeature/en-US/about_ADOptionalFeature.help.txt
- source/DSCResources/MSFT_ADOrganizationalUnit/en-US/about_ADOrganizationalUnit.help.txt
- source/DSCResources/MSFT_ADReplicationSite/en-US/about_ADReplicationSite.help.txt
- source/DSCResources/MSFT_ADReplicationSiteLink/en-US/about_ADReplicationSiteLink.help.txt
- source/DSCResources/MSFT_ADReplicationSubnet/en-US/about_ADReplicationSubnet.help.txt
- source/DSCResources/MSFT_ADServicePrincipalName/en-US/about_ADServicePrincipalName.help.txt
- source/DSCResources/MSFT_ADUser/en-US/about_ADUser.help.txt
- source/DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
This PR updates the PowerShell help files for the ActiveDirectoryDsc module.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/538)
> ActiveDirectoryDsc: Update PowerShell Help

- CHANGELOG.md
- source/DSCResources/MSFT_ADComputer/MSFT_ADComputer.schema.mof
- source/DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt
This PR fixes the `ADComputer` resource `SamAccountName` property description.
- Fixes #529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/540)
> ADComputer: Fix SamAccountName Property Description

- CHANGELOG.md
- Tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1
- Tests/Unit/MSFT_ADComputer.Tests.ps1
- Tests/Unit/MSFT_ADDomain.Tests.ps1
- Tests/Unit/MSFT_ADDomainController.Tests.ps1
- Tests/Unit/MSFT_ADDomainControllerProperties.Tests.ps1
- Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
- Tests/Unit/MSFT_ADDomainTrust.Tests.ps1
- Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
- Tests/Unit/MSFT_ADObjectEnabledState.Tests.ps1
- Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
- Tests/Unit/MSFT_ADUser.Tests.ps1
- Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
This PR removes all unnecessary `Verbose` parameters from function calls in the unit tests to reduce the noise in the unit test output.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/544)
> ActiveDirectoryDsc: Remove Verbose Parameters from Unit Tests

- CHANGELOG.md
- azure-pipelines.yml
This PR updates the Windows image used in the Azure Pipeline from `win1803` to `windows-2019` as the `win1803` image is being retired by Microsoft. Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
- Fixes #551 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/558)
> ActiveDirectoryDsc: Update Azure Pipeline Windows Image

- CHANGELOG.md
- LICENSE
This PR updates the license copyright from `Copyright (c) 2015 Microsoft Corporation.` to `Copyright (c) DSC Community contributors.`
- Fixes #550 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/557)
> ActiveDirectoryDsc: Update License Copyright to Dsc Community Contributors

- .codecov.yml
- CHANGELOG.md
- README.md
- azure-pipelines.yml
- build.yaml
- codecov.yml
This PR enables [Codecov.io](https://codecov.io) support in the Azure DevOps CI/CD pipeline.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/562)
> ActiveDirectoryDsc: Enable Codecov.io Support in the CI Pipeline

- CHANGELOG.md
- source/DSCResources/MSFT_ADDomainFunctionalLevel/README.md
- source/DSCResources/MSFT_ADDomainFunctionalLevel/en-US/about_ADDomainFunctionalLevel.help.txt
- source/DSCResources/MSFT_ADForestFunctionalLevel/README.md
- source/DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
- source/DSCResources/MSFT_ADManagedServiceAccount/README.md
- source/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1
- source/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.schema.mof
- source/DSCResources/MSFT_ADServicePrincipalName/en-US/about_ADServicePrincipalName.help.txt
This PR fixes some miscellaneous spelling errors in the module.
- None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/567)
> ActiveDirectoryDsc: Fix Spelling Errors

- CHANGELOG.md
- azure-pipelines.yml
- When merging a commit with changes only to CHANGELOG.md the CI pipeline
will not run.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/580)
> ActiveDirectoryDsc: CHANGELOG.md will not run CI

- CHANGELOG.md
- azure-pipelines.yml
- Fixes the change log.
Also tests the new azurepipeline.yml configuraiton to see if it works.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/590)
> ActiveDirectoryDsc: Fix CHANGELOG.md

- CHANGELOG.md
- azure-pipelines.yml
This PR changes the Azure DevOps CI pipeline to use Pipeline Artifacts instead of Build Artifacts. This reduces the Pipeline execution time by approximately one minute.
See [What is the difference between build and pipeline artifacts?](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2341) for more information.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/600)
> ActiveDirectoryDsc: Change CI Pipeline from Build to Pipeline Artifact

- CHANGELOG.md
This PR removes some invalid characters from `CHANGELOG.md` which were preventing publishing of the module.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/628)
> ActiveDirectoryDsc: Remove Invalid Characters from CHANGELOG.md

- CHANGELOG.md
This PR updates the `CHANGELOG.md` for the `6.1.0` retracted release.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/640)
> ActiveDirectoryDsc: Update CHANGELOG.md for 6.1.0 Retracted Release

- CHANGELOG.md
- GitVersion.yml
- The component `gitversion` that is used in the pipeline was wrongly configured
when the repository moved to the new default branch `main`. It no longer throws
an error when using newer versions of GitVersion.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/645)
> ActiveDirectoryDsc: Fix GitVersion

- CHANGELOG.md
- RequiredModules.psd1
- build.yaml
This PR pins the versions all the modules in `RequiredModules` to avoid build issues with breaking changes introduced by these modules.
It also adds the `Sampler.GitHubTasks` module which was an undocumented breaking change introduced by https://github.com/gaelcolas/Sampler/pull/240
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/663)
> ActiveDirectoryDsc: Pin All RequiredModules and Add 'Sampler.GitHubTasks'

- CHANGELOG.md
- azure-pipelines.yml
Updates Pipeline from Ubuntu 16.04 to 18.04
- Fixes #667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/668)
> Updated Ubuntu to 18.04 fixes #667

- CHANGELOG.md
- source/build.psd1
- There was a 'build.ps1' file under the source folder than are no longer
required for ModuleBuilder to work.
None.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/687)
> Remove pipeline file no longer required

- CHANGELOG.md
- source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1
- source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.schema.mof
- source/DSCResources/MSFT_ADOrganizationalUnit/en-US/about_ADOrganizationalUnit.help.txt
- tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
Adds DomainController Parameter
- Fixes #563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666)
> ADOrganizationalUnit: Added DomainController Parameter #563

- CHANGELOG.md
- source/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1
Add check at the top of `Set-TargetResource` to cover case when `Invoke-DscResource -Method Set` is called
- Fixes #520
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/707)
> ADServicePrincipalName: Call test at the top of set in case of explicit call to set function

- .vscode/extensions.json
- CHANGELOG.md
Add recommended extensions to extensions.json
- Fixes #622 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/708)
> VS Code: Add recommended extensions in extensions.json
